/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as CompanyCompanyIdRouteImport } from './routes/company.$companyId'
import { Route as CompanyCompanyIdCategoryCategoryIdRouteImport } from './routes/company.$companyId.category.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdRoute = CompanyCompanyIdRouteImport.update({
  id: '/company/$companyId',
  path: '/company/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCompanyIdCategoryCategoryIdRoute =
  CompanyCompanyIdCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => CompanyCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/company/$companyId/category/$categoryId': typeof CompanyCompanyIdCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/company/$companyId/category/$categoryId': typeof CompanyCompanyIdCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/company/$companyId': typeof CompanyCompanyIdRouteWithChildren
  '/company/$companyId/category/$categoryId': typeof CompanyCompanyIdCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecosystem'
    | '/company/$companyId'
    | '/company/$companyId/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecosystem'
    | '/company/$companyId'
    | '/company/$companyId/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/ecosystem'
    | '/company/$companyId'
    | '/company/$companyId/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$companyId/category/$categoryId': {
      id: '/company/$companyId/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/company/$companyId/category/$categoryId'
      preLoaderRoute: typeof CompanyCompanyIdCategoryCategoryIdRouteImport
      parentRoute: typeof CompanyCompanyIdRoute
    }
  }
}

interface CompanyCompanyIdRouteChildren {
  CompanyCompanyIdCategoryCategoryIdRoute: typeof CompanyCompanyIdCategoryCategoryIdRoute
}

const CompanyCompanyIdRouteChildren: CompanyCompanyIdRouteChildren = {
  CompanyCompanyIdCategoryCategoryIdRoute:
    CompanyCompanyIdCategoryCategoryIdRoute,
}

const CompanyCompanyIdRouteWithChildren =
  CompanyCompanyIdRoute._addFileChildren(CompanyCompanyIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  CompanyCompanyIdRoute: CompanyCompanyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
